<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;


class SecurityController extends AbstractController
{
   /**
    * @Route ("/registration", name="security_registration")
    */
   public function registration(Request $request, ObjectManager $manager, UserPasswordEncoderInterface $encoder)
   {
      $user = New user();

      $form = $this->createform(RegistrationType::class,$user);

      $form->handleRequest($request);

      if($form->isSubmitted() && $form->isValid())
      {
         $file = $form->get('picture')->getData();

         $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

          // moves the file to the directory where brochures are stored
          $file->move(
            $this->getParameter('pictures'),
            $fileName
        );


         $user->setPicture($fileName);

      
         $hash = $encoder->encodePassword($user, $user->getPassword());
         $user->setPassword($hash);
         $manager->persist($user);
         $manager->flush();
         
         return $this->redirectToRoute('security_login');
      }

      return $this->render('security/registration.html.twig', [
            'form' => $form->createView()
      ]);
   }

    /**
     * @return string
     */
    public function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


   /**
    * @Route("/login", name="security_login")
    */
   public function login(){
      return $this->render('security/login.html.twig');
   }

   /**
    * @Route("/logout", name="security_logout")
    */
   public function logout() {}
}
